function sdkNotReady() {
    throw new Error('Aspire SDK modules are generated by the Aspire CLI. Run `aspire run` in the aspire directory to replace this stub.');
}

export const ContainerLifetime = {
    Persistent: 'Persistent',
};

export const EndpointProperty = {
    Host: 'Host',
    Port: 'Port',
};

export async function createBuilder() {
    sdkNotReady();
}

export function refExpr(strings, ...values) {
    return strings.reduce((result, part, index) => {
        const value = index < values.length ? String(values[index] ?? '') : '';
        return `${result}${part}${value}`;
    }, '');
}
