
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        environment:
          name: 'production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
          - uses: actions/checkout@v2
      
          - name: Setup Bun
            uses: oven-sh/setup-bun@v1
            
          - name: bun install
            run: bun install --production

          - name: 'Deploy to Azure Web App'
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'blacklist-butler'
              slot-name: 'production'
              publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
              package: .
